# datadir-tip-wlan-kafka-0
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-tip-wlan-kafka-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
