# data-tip-wlan-postgresql-slave-0
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-tip-wlan-postgresql-slave-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
