# db-tip-wlan-opensync-mqtt-broker-0
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-tip-wlan-opensync-mqtt-broker-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
